# Configuração do Banco PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tg_legaldb
spring.datasource.username=postgres
spring.datasource.password=J0403366#
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate (SEM dialeto específico)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração do servidor
server.port=8080
